site_name: Nay Thuta's Portfolio
site_url: https://naythuta.github.io/my-portfolio/
theme:
  name: material
  palette:
    - scheme: default
      primary: '#201F4B'
      accent: '#26A69A'
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: '#201F4B'
      accent: '#26A69A'
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  logo: res/logo.png
  favicon: res/logo.png
# Development server configuration
dev_addr: localhost:8000
watch: [docs, mkdocs.yml]

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Projects:
    - Overview: projects.md
    - Sustainable Irrigation System: projects/sustainable-irrigation-system.md
    - WormBrews: projects/wormbrews.md
    - Patient Sentiment Analysis: projects/patient-sentiment-analysis.md
  - About Me: about.md
  - Contact: contact.md

extra_css:
  - extra.css