site_name: Nay Thuta's Portfolio
site_url: https://naythuta.github.io/my-portfolio/
theme:
  name: material
  palette:
    scheme: slate
    primary: blue grey
    accent: blue
  features:
    - content.code.copy
    - content.code.annotate
    - content.code.highlight
    - content.code.show_language
# Development server configuration
dev_addr: localhost:8000
watch: [docs, mkdocs.yml]

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Projects:
    - Overview: projects.md
    - Sustainable Irrigation System: projects/sustainable-irrigation-system.md
    - WormBrews: projects/wormbrews.md
    - Patient Sentiment Analysis: projects/patient-sentiment-analysis.md
  - About Me: about.md
  - Contact: contact.md